name: Run tests on pull request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      MOREMCMETA_MAVEN_USER: ${{ secrets.MOREMCMETA_MAVEN_USER }}
      MOREMCMETA_MAVEN_PASS: ${{ secrets.MOREMCMETA_MAVEN_PASS }}
    steps:
      - uses: actions/checkout@3ba5ee6fac7e0e30e2ea884e236f282d3a775891

      - uses: actions/setup-java@308abcba03229002f0055e17d79d00c32fca160f
        with:
          java-version: 17
          distribution: temurin

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@9aa31f26bc8e536d1faf4b332bb8365350743a18

      - name: Run tests
        uses: gradle/gradle-build-action@cfc50b189af149aeb55f94103f47753382d88d33
        with:
          arguments: test