name: Run tests on pull request
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - uses: actions/setup-java@5b36705a13905facb447b6812d613a06a07e371d
        with:
          java-version: 17
          distribution: temurin

      - name: Ensure Gradle wrapper is executable
        run: chmod +x ./gradlew

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@859c33240bd026ce8d5f711f5adcc65c2f8eafc1

      - name: Run tests
        uses: gradle/gradle-build-action@8be955ee80297c9525ad04fe8610d12c3be14bb0
        with:
          arguments: test